# MAIB Incident Type Classifier Configuration

# Model Configuration
model:
  name: "microsoft/deberta-v3-base"
  max_length: 256
  num_labels: 11
  gradient_checkpointing: true

# Training Configuration
training:
  output_dir: "outputs"
  learning_rate: 2e-5
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  num_train_epochs: 3
  eval_strategy: "epoch"
  save_strategy: "epoch"
  load_best_model_at_end: true
  metric_for_best_model: "macro_f1"
  logging_steps: 50
  report_to: "none"

  # Optimization
  fp16: true
  bf16: false
  optim: "adamw_torch"
  lr_scheduler_type: "linear"
  warmup_ratio: 0.1
  weight_decay: 0.01

  # Data Loading
  dataloader_pin_memory: true
  dataloader_num_workers: 2
  eval_accumulation_steps: 4
  torch_compile: false

# Data Configuration
data:
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1
  random_seed: 42
  num_proc: null  # Will be set to max(1, cpu_count() // 2)

# Evaluation Configuration
evaluation:
  metrics: ["accuracy", "macro_f1", "weighted_f1"]
  eval_split: "validation"

# Inference Configuration
inference:
  top_k: 3
  max_length: 256
  device: "auto"  # Will be set to "cuda" if available, else "cpu"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/training.log"
